# 20171228 6.14: ActiveJob and Advanced ActionCable
# generated by $ rails generate job comment_update
require 'rails_helper'

RSpec.describe CommentUpdateJob, type: :job do
  pending "add some examples to (or delete) #{__FILE__}"
end
