development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://yobmkgvterllwp:1cc393c1d76a0fb7aa265ca7f7b97f17f0d3a837e5e7825e47cd567f87bb81c9@ec2-50-17-217-166.compute-1.amazonaws.com:5432/dah1rjvlopuj7c
  channel_prefix: nameofapp_production

