# 20171228 6.14: ActiveJob and Advanced ActionCable
# generated by $ rails generate job comment_update
class CommentUpdateJob < ApplicationJob
  queue_as :default

  # def perform(*args)
  # replace following for better readability
  def perform(comment, current_user)
    # Do something later
    ProductChannel.broadcast_to(comment.product_id, comment: render_comment(comment, current_user), average_rating: comment.product.average_rating)
  end

  private

  def render_comment(comment, current_user)
  	CommentsController.render(partial: 'comments/comment', locals: { comment: comment, current_user: current_user })
	end


end


